AWSTemplateFormatVersion: 2010-09-09

Parameters:

  VPC1CidrBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: Enter a CIDR range for the VPC.

  SN1CidrBlock:
    Type: String
    Default: 10.0.1.0/24
    Description: Enter a CIDR range for the VPC.
  
  LinuxImageId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  PrismaCloudS3Bucket:
    Type: String
    Default: s3://159843181355-prisma-cloud-distribution
    Description: S3 path to bucket containig tyhe PrismaCloud distribution

  PrismaCloudDistribution:
    Type: String
    Default: prisma_cloud_compute_edition_19_11_512.tar.gz
    Description: PrismaCloud Distribution File

  PrismaCloudHome:
    Type: String
    Default: /opt/twistlock
    Description: PrismaCloud Home Directory
  
Mappings: {}

Conditions: {}

Outputs:

  PublicDnsName:
    Description: DNS name for PrismaCloud Console
    Value: 
      Fn::GetAtt:
        - PrismaCloudInstance
        - PublicDnsName    

Resources:

  VPC1:
    Type: 'AWS::EC2::VPC'
    Properties: 
      CidrBlock: !Ref VPC1CidrBlock
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: prismacloud-vpc
  
  SN1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC1
      CidrBlock: !Ref SN1CidrBlock
      MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: prismacloud-pub-sn

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: Name
          Value: prismacloud-igw

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC1
  
  EIP:
   DependsOn: InternetGatewayAttachment
   Type: AWS::EC2::EIP
   Properties:
      Domain: vpc
  
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC1
      Tags: 
        - Key: Name
          Value: prismacloud-pub-rt
  
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref SN1

  PrismaCloudInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      NetworkInterfaces:
        - SubnetId: !Ref SN1
          DeviceIndex: 0
          GroupSet: 
            - !Ref SG1
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 24
      InstanceType: t2.medium
      ImageId: !Ref LinuxImageId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          yum install docker -y
          sudo service docker start
          usermod -a -G docker ec2-user
      Tags: 
        - 
          Key: "Name"
          Value: "PrismaCloudInstance"
        - 
          Key: "SSMType"
          Value: "PrismaCloudInstance"
        - 
          Key: "SSMManaged"
          Value: "True"
      IamInstanceProfile: !Ref PrismaInstanceProfile
  
  PrismaInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: PrismaInstanceProfile
      Roles: 
        - !Ref PrismaInstanceRole
  
  PrismaInstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement: 
          - 
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess

  SG1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Prisma Console HTTPS
      VpcId: !Ref VPC1
      Tags:
        - Key: Name
          Value: prismacloud-srv-sg
      SecurityGroupIngress:
      - IpProtocol: TCP
        FromPort: 8083
        ToPort: 8083
        CidrIp: 0.0.0.0/0
      - IpProtocol: TCP
        FromPort: 8084
        ToPort: 8084
        CidrIp: 0.0.0.0/0
  
  PrismaCloudInstall:
    Type: 'AWS::SSM::Document'
    Properties:
      DocumentType: Automation
      Content:
        description: >-
          # PrismaCloud Install and Configure

          This document downsloads the PrismaCloud distribution from an S3 bucket and deploys it to the /opt/twistlock folder.
        schemaVersion: '0.3'
        parameters:
          InstanceId: 
            type: StringList
        mainSteps:
          - name: DownloadPrismaCloudDistro
            action: 'aws:runCommand'
            inputs:
              DocumentName: AWS-RunShellScript
              InstanceIds:
                - '{{InstanceId}}'
              Parameters:
                commands: 
                  - >-
                    sudo mkdir /opt/twistlock
                  - sudo aws s3 cp s3://159843181355-prisma-cloud-distribution/prisma_cloud_compute_edition_19_11_512.tar.gz /opt/twistlock
            description: Download the server from S3 bucket.
            onFailure: Continue
          - name: UnzipPrismaCloudDistro
            action: 'aws:runCommand'
            inputs:
              DocumentName: AWS-RunShellScript
              InstanceIds:
                - '{{InstanceId}}'
              Parameters:
                commands: >-
                  sudo tar -xzf /opt/twistlock/prisma_cloud_compute_edition_19_11_512.tar.gz -C /opt/twistlock/
            description: Unzips the server to /opt/twistlock
            onFailure: Continue
          - name: InstallPrismaCloud
            action: 'aws:runCommand'
            inputs:
              DocumentName: AWS-RunShellScript
              InstanceIds:
                - '{{InstanceId}}'
              Parameters:
                commands: >-
                  sudo /opt/twistlock/twistlock.sh -s onebox
            description: Installs the server to /opt/twistlock/
            onFailure: Continue